# Generated by Django 5.2.6 on 2025-09-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=0)),
                ('project_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('universal', 'Universal QA Standards'), ('project_specific', 'Project Specific'), ('onboarding', 'Onboarding'), ('troubleshooting', 'Troubleshooting'), ('tools', 'Tools & Systems')], max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('project_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa_api.team')),
            ],
        ),
        migrations.CreateModel(
            name='QAQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('user_feedback', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa_api.team')),
            ],
        ),
    ]
