# Generated by Django 5.2.6 on 2025-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_api', '0002_faq_knowledgebase_qaquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='key_contacts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
