# Generated by Django 5.2.6 on 2025-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_api', '0003_team_key_contacts_team_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='key_contacts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
